sonar.projectKey=frank-mendez_ResumeIQ
sonar.organization=frank-mendez
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/.output/**,**/routeTree.gen.ts
sonar.coverage.exclusions=src/routes/auth.callback.tsx,src/routes/dashboard/index.tsx,src/routes/login.tsx,src/components/dashboard/DashboardUploadSection.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json